"""add likes attribute to travelposts model

Revision ID: 879c33aff5f5
Revises: b26adae8fbae
Create Date: 2021-07-26 09:24:00.233988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879c33aff5f5'
down_revision = 'b26adae8fbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travelposts', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travelposts', 'likes')
    # ### end Alembic commands ###
